name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libffi-dev libssl-dev python3-dev python3-venv
        python3 -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install buildozer cython

    - name: Build APK
      run: |
        . venv/bin/activate
        buildozer init
        buildozer -v android debug
        mkdir -p output
        cp build/outputs/apk/debug/*.apk output/

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-apk
        path: output/*.apk
